---
image: python:3.9-slim

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PROJECT_SOURCE_DIR: "apixy"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - python -m venv venv
  - source venv/bin/activate

stages:
  - lint
  # - test
  # - deploy

lint:
  stage: lint
  script:
    - pip install pre-commit
    - pre-commit install
    - pre-commit run --all-files

# test:
#   stage: test
#   script:
#     - pip install -r requirements/dev.txt
#     - pytest
