---
version: "3"
services:
  api:
    image: apixy-be
    command: []
  migrate:
    image: apixy-be
  db:
    volumes: []
  tests:
    build: ./Dockerfile.itest
    volumes:
      - "./tests/integration:/tests"
    depends_on:
      - api
volumes: {}
