version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["sh", "-c", "uvicorn apixy.app:app --host 0.0.0.0 --reload"]
  db:
    image: postgres:13
    ports:
    - 5432:5432
    env_file: .env
    restart: unless-stopped
    volumes:
      - apixy_db:/var/lib/postgresql

volumes:
  apixy_db:
